import { ArrowLeft, ArrowRight, Building2, Check, CreditCard, Minus, Paintbrush, Plus, ScanLine } from "lucide-react";
import { useState } from "react";
import { Link, Navigate, useParams } from "react-router";
import Footer from "../components/layout/Footer";
import { useApp } from "../context/AppContext";
import { customDesignShowcaseImage } from "../generated/customDesignShowcaseImage";
import { serviceSignImage } from "../generated/serviceSignImage";

const cardImages = ["vizora-tajikistan-independence.webp", "vizora-tajikistan-hissar.webp", "vizora-tajikistan-arch.webp", "vizora-tajikistan-building.webp", "vizora-tajikistan-somoni.webp", "vizora-tajikistan-palace.webp"];
const content = {
  "custom-design": { icon: Paintbrush, order: "digital", visual: "cards", ru: ["Индивидуальный дизайн визитки", "Создадим визитку, которая соответствует вашей профессии, стилю и фирменным цветам.", ["Персональная концепция", "Электронная и печатная версии", "QR-код и подготовка файлов"]], tj: ["Дизайни инфиродии варақа", "Варақаеро месозем, ки ба касб, услуб ва рангҳои фирмавии шумо мувофиқ аст.", ["Консепсияи инфиродӣ", "Нусхаҳои электронӣ ва чопӣ", "QR-код ва омодасозии файлҳо"]], en: ["Custom business card design", "A distinctive card tailored to your profession, visual style and brand colors.", ["Personal concept", "Digital and print versions", "QR code and production files"]] },
  "organization-turnkey": { icon: Building2, order: "turnkey", visual: "organization", ru: ["Визитки организации под ключ", "Создадим единую цифровую систему визиток для руководителей, отделов и сотрудников.", ["Единый корпоративный дизайн", "Создание карточек сотрудников", "Страница организации и общий QR-код"]], tj: ["Варақаҳои ташкилот бо омодасозии пурра", "Барои роҳбарон, шуъбаҳо ва кормандон низоми ягонаи варақаҳои рақамиро месозем.", ["Дизайни ягонаи корпоративӣ", "Сохтани варақаҳои кормандон", "Саҳифаи ташкилот ва QR-код"]], en: ["Turnkey organization cards", "A unified digital business-card system for managers, departments and employees.", ["Unified corporate design", "Employee card setup", "Organization page and QR code"]] },
  "nfc-cards": { icon: CreditCard, order: "nfc", visual: "nfc", ru: ["NFC-карты Vizora", "Выберите готовый дизайн, укажите количество и закажите карту с мгновенным открытием вашей визитки.", ["Открытие одним касанием", "Работает без установки приложения", "Прочная полноцветная карта"]], tj: ["Кортҳои NFC-и Vizora", "Дизайнро интихоб кунед, миқдорро нишон диҳед ва кортеро фармоиш диҳед, ки варақаи шуморо бо як ламс мекушояд.", ["Кушодан бо як ламс", "Бе насби барнома кор мекунад", "Корти мустаҳками ранга"]], en: ["Vizora NFC cards", "Choose a design and quantity, then order a card that opens your profile with one tap.", ["One-tap opening", "No app installation required", "Durable full-color card"]] },
  "nfc-qr-signs": { icon: ScanLine, order: "desk", visual: "signs", ru: ["NFC- и QR-таблички", "Выберите формат для стойки, стола, двери или зоны обслуживания клиентов.", ["NFC и QR в одном решении", "Ваш логотип и фирменные цвета", "Несколько размеров и материалов"]], tj: ["Лавҳаҳои NFC ва QR", "Форматро барои пештахта, миз, дар ё минтақаи хизматрасонӣ интихоб кунед.", ["NFC ва QR дар як маҳсулот", "Лого ва рангҳои фирмавии шумо", "Андоза ва маводҳои гуногун"]], en: ["NFC and QR signs", "Choose a format for a counter, desk, door or customer service area.", ["NFC and QR in one product", "Your logo and brand colors", "Multiple sizes and materials"]] }
} as const;

export default function ServiceDetailPage() {
  const { serviceId } = useParams(); const { language } = useApp(); const service = content[serviceId as keyof typeof content];
  const [variant, setVariant] = useState(0); const [quantity, setQuantity] = useState(1);
  if (!service) return <Navigate to="/services" replace />;
  const [title, description, benefits] = service[language]; const Icon = service.icon;
  const labels = language === "ru" ? { back: "Все услуги", included: "Что входит", examples: "Выберите вариант", quantity: "Количество", order: "Заказать", process: "Как мы работаем", steps: ["Получаем заявку", "Согласовываем детали", "Изготавливаем и подключаем"] } : language === "tj" ? { back: "Ҳамаи хизматҳо", included: "Ба хизмат дохил мешавад", examples: "Навъро интихоб кунед", quantity: "Миқдор", order: "Фармоиш додан", process: "Тартиби кор", steps: ["Дархостро мегирем", "Ҷузъиётро мувофиқа мекунем", "Омода ва пайваст мекунем"] } : { back: "All services", included: "What is included", examples: "Choose an option", quantity: "Quantity", order: "Order now", process: "How it works", steps: ["We receive your request", "We confirm the details", "We produce and connect"] };
  const signVariants = language === "ru" ? ["Настольная NFC", "QR для стойки", "Настенная", "NFC-наклейка"] : language === "tj" ? ["NFC-и рӯимизӣ", "QR барои пештахта", "Деворӣ", "Часпак бо NFC"] : ["Desktop NFC", "Counter QR", "Wall sign", "NFC sticker"];
  const variants = service.visual === "signs" ? signVariants : cardImages.map((_, i) => `${language === "tj" ? "Дизайн" : language === "en" ? "Design" : "Дизайн"} ${i + 1}`);
  const orderUrl = `/service-order?service=${service.order}&qty=${quantity}&variant=${encodeURIComponent(variants[variant])}`;
  return <><main className="service-detail-page"><div className="services-orb services-orb-one" /><div className="services-orb services-orb-two" /><section className="site-container service-detail-shell"><Link className="service-back" to="/services"><ArrowLeft size={17} />{labels.back}</Link><header className="service-detail-head"><span className="services-choice-icon"><Icon size={28} /></span><div><span className="section-label">VIZORA SERVICES</span><h1>{title}</h1><p>{description}</p></div></header><div className="service-detail-grid"><section className="service-showcase">{service.visual === "organization" ? <div className="organization-service-visual"><Building2 size={54} /><strong>VIZORA.TJ</strong><span>01</span><span>02</span><span>03</span></div> : service.visual === "cards" ? <img className="service-single-image" src={customDesignShowcaseImage} alt={title} /> : service.visual === "signs" ? <img className="service-sign-image" src={serviceSignImage} alt="NFC и QR таблички Vizora" /> : <div className="service-card-gallery">{cardImages.map((image, index) => <button type="button" className={variant === index ? "active" : ""} onClick={() => setVariant(index)} key={image}><img src={`${import.meta.env.BASE_URL}images/cards/${image}`} alt={`${labels.examples} ${index + 1}`} /><span>{variants[index]}</span></button>)}</div>}</section><aside className="service-order-panel"><h2>{labels.included}</h2><ul>{benefits.map(item => <li key={item}><Check size={17} />{item}</li>)}</ul>{(service.visual === "nfc" || service.visual === "signs") && <><label>{labels.examples}</label><div className="service-variant-list">{variants.map((item, index) => <button type="button" className={variant === index ? "active" : ""} onClick={() => setVariant(index)} key={item}>{item}</button>)}</div><label>{labels.quantity}</label><div className="service-quantity"><button type="button" onClick={() => setQuantity(Math.max(1, quantity - 1))}><Minus size={18} /></button><strong>{quantity}</strong><button type="button" onClick={() => setQuantity(quantity + 1)}><Plus size={18} /></button></div></>}<Link className="button button-primary button-large w-full" to={orderUrl}>{labels.order}<ArrowRight size={18} /></Link></aside></div><section className="service-process"><span className="section-label">{labels.process}</span><div>{labels.steps.map((step, index) => <article key={step}><b>0{index + 1}</b><p>{step}</p></article>)}</div></section></section></main><Footer /></>;
}
